name: conjur-action

on:
  workflow_call:
    secrets:
      sql_username:
        description: 'CONJUR SECRET SQL USERNAME'
        required: true
      sql_password:
        description: 'CONJUR SECRET SQL PASSWORD'
        required: true
  push:
    branches:
      - master
  pull_request:

jobs:
  authn-jwt:
    runs-on: self-hosted
    
    permissions:
      id-token: 'write'
      contents: 'read'

    outputs:
      sql_username: ${{ secrets.sql_username }}
      sql_password: ${{ secrets.sql_password }}

    steps:
      - uses: actions/checkout@v1
      
      - name: Use CyberArk Conjur Secret Fetcher Action w/ GitHub JWT
        id: conjur-secrets
        uses: ./  # Repositório local ou ação personalizada
        with:
          url: https://latamlab.secretsmgr.cyberark.cloud/api
          account: conjur
          authn_id: github
          secrets: data/vault/dev-demo-cred/appuser_db/username|sql_username;data/vault/dev-demo-cred/appuser_db/password|sql_password
          
      - name: Set sql_username and sql_password as Outputs
        run: |
          echo "sql_username=${{ secrets.sql_username }}" >> $GITHUB_ENV
          echo "sql_password=${{ secrets.sql_password }}" >> $GITHUB_ENV

      - name: Print GITHUB_ENV Content in authn-jwt
        run: cat $GITHUB_ENV  # Imprime o conteúdo do GITHUB_ENV para depuração

      - name: Clean Workspace
        uses: AutoModality/action-clean@v1.1.0

  check_mysql:
    runs-on: self-hosted
    needs: authn-jwt

    steps:
      - name: Print GITHUB_ENV Content in check_mysql
        run: cat $GITHUB_ENV  # Imprime o conteúdo do GITHUB_ENV para depuração

      - name: Check MySQL Connection
        run: |
          echo "Verificando conexão com o banco de dados..."
          echo "Usando usuário: ${{ needs.authn-jwt.outputs.sql_username }}"
          mysql -h 10.78.10.171 -u "${{ needs.authn-jwt.outputs.sql_username }}" -p"${{ needs.authn-jwt.outputs.sql_password }}" -e "SHOW PROCESSLIST;" || exit 1
