name: conjur-action Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  authn-jwt:
    runs-on: self-hosted
    
    permissions:
      id-token: 'write'
      contents: 'read'

    steps:
      - uses: actions/checkout@v1
      - name: Use CyberArk Conjur Secret Fetcher Action w/ GitHub JWT
        uses: ./
        with:
          url: https://latamlab.secretsmgr.cyberark.cloud/api
          account: conjur
          authn_id: github
          secrets: data/vault/dev-demo-cred/appuser_db/username|sql_username;data/vault/dev-demo-cred/appuser_db/password|sql_password
      - name: Check SQL_USERNAME Outside Docker Container for Secret Masking
        run: printenv SQL_USERNAME | sed 's/./& /g'
      - name: Check SQL_PASSWORD Outside Docker Container for Secret Masking
        run: printenv SQL_PASSWORD | sed 's/./& /g'
      - name: Clean Workspace
        uses: AutoModality/action-clean@v1.1.0

  show-jwt-claims:
    runs-on: ubuntu-latest

    steps:
      - name: Checar o código
        uses: actions/checkout@v2

      - name: Obter e decodificar o JWT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Obtendo o JWT..."
          JWT=$(curl -H "Authorization: Bearer $GITHUB_TOKEN" https://api.github.com)
          echo "JWT Bruto: $JWT"
          echo $JWT | cut -d "." -f2 | base64 -d | jq .    


    

