name: Print Secrets

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  print-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Print Secrets
        run: ./print_secrets.sh
        env:
          CX_CLIENT_ID: ${{ secrets.CX_CLIENT_ID }}
          CX_CLIENT_SECRETS: ${{ secrets.CX_CLIENT_SECRETS }}
